### ISSUE TITLE
Any results about SENet on Coco

### ISSUE THREAD

**Issue by zehuichen123** [MUST-AI-Lab/mmdetection#1]
Hi, I'm trying to adopt SENet154 on my own model on mmdet. However, SENet is not officially supported by MMDetection repo. I notice that your repo has an implementation of SENet. Have you validated SENet performance? Thanks!

**Comment by Linxuxin** [comment]
Thanks for your attention to our repo. We have not yet validated SENet on COCO. You can have a try to do it.

**Comment by zehuichen123** [comment]
I see~ Thx for your response, I will have a try!
